### ISSUE TITLE
%F %L %location pattern not working

### ISSUE THREAD

**Issue by williamlee1982** [cjbhaines/Log4Net.Async#15] opened 2015-10-29 10:26 UTC
the original appenders work fine with %F %L and %location conversion pattern, but once using ParallelForwardingAppender to forward to a RollingFileAppender, log4net logs nothing at all. Please check if this is an issue, and thanks very much for your work!

**Comment by cjbhaines** [comment] 2016-01-27 10:07
Duplicate of #12

**Closed by cjbhaines** 2016-01-27 10:07 UTC
